version: '3'
services:
  flask-app:
    build:
      context: image
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flask-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
