name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: |
        set -e
        docker build image --tag ultraviolence/my-app-backend:latest
        docker push ultraviolence/my-app-backend:latest
      env:
        DOCKER_BUILDKIT: 1
